### ISSUE TITLE
Add app.json for review apps

### ISSUE THREAD

**Issue by strand** [OSFeels/OSFeels.com#30]
https://blog.heroku.com/archives/2015/5/19/heroku_review_apps_beta
https://blog.heroku.com/archives/2014/5/22/introducing_the_app_json_application_manifest
https://devcenter.heroku.com/articles/app-json-schema

**Comment by khjrtbrg** [comment]
:+1:

**Comment by strand** [comment]
When I filed I couldn't figure out how to generate this. Then I found the button.
