### ISSUE TITLE
Move CFP Call to Action up

### ISSUE THREAD

**Issue by strand** [OSFeels/OSFeels.com#34]
The CFP Call to Action is not visible in the first or second page when I scroll on a MBP 15" fullscreen browser. This is our most important content.

![screen_shot_2015-06-27_at_10_03_21_am](https://cloud.githubusercontent.com/assets/509611/8393076/e7894ccc-1cb3-11e5-842a-c52c684cd99e.png)

Please make this visible above the fold. I believe you can also reduce the font size on our tagline so that it only takes one line.

**Comment by khjrtbrg** [comment]
Closing this one, since the CFP closed.
