### ISSUE TITLE
Tickets Design Decision Time!

### ISSUE THREAD

**Issue by khjrtbrg** [OSFeels/OSFeels.com#48]
Hey all,

It looks like the tickets branch's design was changed before it got merged in. I did some work this evening to make it more consistent with Amy's design. I'm concerned, however, that it looks almost indistinguishable from the homepage at first glance. Given that, and the fact that I've also been having some issues getting things to line up consistently, I brought back the previous one column layout in another branch as an alternate option.

[Three column option](https://github.com/OSFeels/OSFeels.com/tree/horizontal-tickets)
![three-column](https://cloud.githubusercontent.com/assets/7614497/9079291/7bfcf57c-3afd-11e5-8405-3f087bcea4ff.png)

[One column option](https://github.com/OSFeels/OSFeels.com/tree/vertical-tickets)
![one-column](https://cloud.githubusercontent.com/assets/7614497/9079297/854704ba-3afd-11e5-8415-558f544ad2bc.png)

Thoughts? Preferences? Changes?

:purple_heart:

**Comment by strand** [comment]
Kristina, go with the one-column option. :ship:
