### ISSUE TITLE
Add an Info page

### ISSUE THREAD

**Issue by kerrizor** [OSFeels/OSFeels.com#68]
..or something, but a big page that has details about

- [ ] Venue, including it's location, ADA stuff (elevator and headsets for hearing impaired)
- [ ] How To Get Here:
  - [ ] Where to Park
  - [ ] Bus lines that get you to the venue, and a link to the "How To Ride Transit" videos
  - [ ] SeaTac airport, how to ride the train?
- [ ] nearest 3 hotels (Silver Cloud... downtown? meh.. I don't know! :D something on a busline?)
- [ ] map of Venue and our 5 favorite coffee shops
- [ ] same, but with 8 good places to eat of various cuisines and price points
- [ ] anything else I'm forgetting that is good to know

**Comment by kerrizor** [comment]
Note that I'm happy to write the copy here, if people create the page itself.

**Comment by khjrtbrg** [comment]
@kerrizor I'll start working on this!
