### ISSUE TITLE
Speaker bios cannot contain links

### ISSUE THREAD

**Issue by strand** [OSFeels/OSFeels.com#74]
The speaker bios are presented as a tooltip. Both Audrey Eschright and Eric Holscher submitted bios with links in them. Tooltips can only handle plaintext, not HTML, to resolve this issue we'll have to change how speaker bios are displayed.

**Comment by khjrtbrg** [comment]
What do you think about putting bios below talk descriptions?

**Comment by strand** [comment]
I like it, except at the moment we have a wall of text problem. Maybe we could trim down talk descriptions or reveal on click on desktop view…
